### ISSUE TITLE
global listen mode no longer working

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#198]
When I try to listen to a project that does not have geo-listen enabled, it plays the speaker audio, but not any assets if I do not send a lat/lon parameters with ```request_stream``` or ```modify_stream```.  If I do send lat/lon parameters, even though the project is flagged as not a geo-listen project, the assets within range are played, but no other assets are played.  This behavior leads me to believe that there is no longer a distinction being made between geo-listen and global-listen projects i.e. all projects are being treated as geo-listen.

This could have changed when the whole refactoring of the code regarding the ```playlist``` occurred as this is the code that deals with this stuff.  I haven't yet looked into earlier code to see how it was previously handled, but I believe the proper approach is that if the project is flagged as global-listen (ie geo_listen_enabled = false), when the ```playlist``` is being created, any lat/lon parameters should be ignored and the ```playlist``` should be populated with ALL recordings in the project per the given tag filters instead of none of the assets (not in range) as is happening now.

I will investigate the code more, but wanted to record the issue based on my initial tests.

**Comment by eosrei** [comment]
Haha, yes, this is why we need unit tests and code comments. I'll look into it.

**Comment by eosrei** [comment]
> when the playlist is being created, any lat/lon parameters should be ignored and the playlist should be populated with ALL recordings in the project per the given tag filters instead of none of the assets (not in range) as is happening now.

This sounds right and is straightforward to implement.
