### ISSUE TITLE
Document local settings

### ISSUE THREAD

**Issue by eosrei** [roundware/roundware-server#201]
There are production overrides needed for the server settings. One example is the SMTP email settings. We need a standard documented method to override.

**Comment by hburgund** [comment]
We used to use a simple ```local_settings.py``` file that was automatically included if present.  We still do this in ```settings/dev.py```:

https://github.com/hburgund/roundware-server/blob/develop/roundware/settings/dev.py#L3

This method seems to work nicely and I believe it is the standard approach.  Should we just re-implement, document and provide a sample ```local_settings.py``` file in the repo?  Or is this where something like Ansible can provide a much more robust, secure and flexible solution?

**Comment by eosrei** [comment]
The main issue is that we need to put it outside of the regular code storage area so that the code can be updated efficiently
