### ISSUE TITLE
first playback recording is always panned hard left

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#203]
(xfer from old Trac system: http://roundware.org/trac/ticket/147)

composition settings are set pan to the middle, but the first recording seems to always be hard left...very weird. after the first one, they are in the middle as expected.

I am adding this issue because Jonah noted it in his most recent testing.  It has existed for a while , but I don't think it's consistent.  Seems to only affect the first asset, so not a huge problem, but definitely weird and a bit annoying.

**Comment by eosrei** [comment]
If `target_pan_step` and `pan_step_size` start equal to zero, then `self.target_pan_pos` will be -1.
```python
self.target_pan_pos = -1 + target_pan_step * pan_step_size
```
src: https://github.com/roundware/roundware-server/blob/68d096cf07b158ff89aa0aa198b3b3e2fcda722f/roundwared/audiotrack.py#L194

According to the docs, -1 is hard left: http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-audiopanorama.html

**Comment by eosrei** [comment]
This issue brings up a good point: You must document what the RW panning system is supposed to do.

**Comment by hburgund** [comment]
this will go away with CSM, so closing
