### ISSUE TITLE
improve audio "pause" handling

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#207]
The perennial challenges are these:
- if you actually pause the streaming audio during a session, it will buffer on the device (at least for a little while) and then when you un-pause, it will pick up where it left off thus you will be hearing audio with much more latency.  This is not acceptable.  If it was possible to limit the amount of buffering in the media player, that could help.
- "pause" could simply mean mute on the client, in which case the audio still is sent to the device but isn't heard.  This has issues of bandwidth waste and potential to get in the way of other network activity.  Also, this would cause assets to be played and then added to the `timed_ban` list so listeners would miss out hearing those assets.
- we could startup the stream ie `request_stream` with the same session_id again each time the stream is un-paused, but this takes a little while for the server to generate the stream and buffer it on the device for a few seconds, so it's not ideal.  It does, however, not increase latency.

An idea:
- when pause is pressed, send a message to the server that tells it to stop adding assets to the stream.  Just keep the music going, but don't add any more assets even if there are some remaining in the `playlist`
- also, stop the client from sending `move_listener` requests as that would be wasteful
- when un-pause is pressed, immediately send a `move_listener` with the current location and mount the stream url in the media-player again.
- continue to send `heartbeats` while stream is paused so it doesn't get cleaned up on the server

I need to consider this approach more carefully, but wanted to document it to discuss at some point.

**Comment by eosrei** [comment]
I imagine you're hoping for a different answer, but this is another reason for in-device audio.

**Comment by hburgund** [comment]
Yes, of course that will make a big difference for sure.  We'll still need to discuss how to handle it, though, because the standard pause functions on most media players aren't going to handle it the way we need.  I just wanted to get this idea down, as I think it will be useful for both in-device and server-based audio mixing scenarios.  But if in-device is coming soon enough, it may not be worth implementing anything significant on the server.
