### ISSUE TITLE
Authorization header stripped by Apache

### ISSUE THREAD

**Issue by grayb** [roundware/roundware-server#214]
In the installation script install.sh, in a non-vagrant environment, Apache is configured via a VirtualHost.

While using the token facilities of the Django Rest Framework, token authorization is handled by an "Authorization" header sent with the request.

As configured, Apache is removing that header, and DRF never receives it.  I found a discussion of the problem here:
https://github.com/tomchristie/django-rest-framework/issues/488

I will submit a fix for this shortly.

**Comment by eosrei** [comment]
Fixed by #215

**Comment by lemonprogis** [comment]
Hey guys, where did you put this line? i have put it in my site-enabled .conf file but still seems to fail. any help would be most appreciated. thanks.
