### ISSUE TITLE
roundware.api1.commands.add_asset_to_envelope() needs refactoring

### ISSUE THREAD

**Issue by 13rac1** [roundware/roundware-server#226]
https://github.com/roundware/roundware-server/blob/7a4843864f73ae17261d90065d106c4878d8e011/roundware/api1/commands.py#L528

This function is too complicated. It needs to be refactored into multiple functions such as `create_asset()` and `create_envelope()`. Probably can be handled in the models.py

**Comment by hburgund** [comment]
`api/1/` is no longer being supported/updated, so closing this issue without completion
