### ISSUE TITLE
Django 1.9 is released. Time to upgrade

### ISSUE THREAD

**Issue by 13rac1** [roundware/roundware-server#229]
https://docs.djangoproject.com/en/1.8/releases/1.8/

**Comment by hburgund** [comment]
awesome...looks like 1.8 has some cool updates with geo stuff as well as Postgres integration, which we will hopefully be migrating to soon as well.  Maybe simultaneously with this upgrade?

**Comment by 13rac1** [comment]
I think I've located/fixed the only change blocking the 1.8 upgrade here: https://github.com/eosrei/roundware-server/commit/4f2a87376fb4d54565da6878c522fb0a84cfac74 Other than that it should be a simple upgrade.

Postgres will be more of a hassle, since we need to do a data conversion. Maybe dump the database to a fixture? That could make it easier.

**Comment by 13rac1** [comment]
Update: https://www.djangoproject.com/weblog/2015/dec/01/django-19-released/

> With the release of Django 1.9, Django 1.7 has reached end-of-life. Django 1.7.11 is the final release of the 1.7 series and all users are encouraged to upgrade to Django 1.8+ as soon as possible so they can continue to receive security updates. Django 1.8 LTS will receive security updates until April 2018.
