### ISSUE TITLE
server no longer converts caf files uploaded from iOS devices to mp3/wav

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#232]
The server used to be able to handle `caf` files uploaded from iOS devices by converting them to `mp3` and `wav` using `pacpl`.  For some reason, this no longer works.

Using the following correct conversion command:

```
$ /usr/bin/pacpl --to wav --outdir /var/www/roundware/rwmedia /var/www/roundware/rwmedia/20150325-102535-140.caf 
```

the following error is thrown:

```
Perl Audio Converter - 4.0.5
Converting:  [20150325-102535-140.caf] -> [wav] decode failed with exit status: 256
Total files converted: 0, failed: 1
```

It fails similarly trying to convert to `mp3`.  This appears to have nothing to do with the Roundware code, but rather some change in either `pacpl` or the specifics of the `caf` format produced by iOS 8.

We get around this issue now by having the client do the conversion locally before uploading.  This also does tend to produce a smaller file for upload which is helpful, but as a general rule, it makes more sense for the server to handle audio conversions than the client.

**Comment by 13rac1** [comment]
Please try the official ffmpeg. The ffmpeg vs avconv fight may be related.

**Comment by hburgund** [comment]
Just learned that iOS 8 is capable of recording directly to `m4a` format rather than `caf`, so there is no longer any need to handle `caf` files anywhere in Roundware.  `m4a` files are handled fine by the RW server currently, so I am closing this issue until there is another requirement for `caf` files.

**Comment by 13rac1** [comment]
Since it's broken _and_ we aren't using it, should we remove "support" for caf files from the codebase? Best not to leave known broken functionality.

**Comment by hburgund** [comment]
agreed...thx for https://github.com/roundware/roundware-server/issues/235
