### ISSUE TITLE
Create script to generate new fixtures when schema is changed

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#260]
Every time we have a schema change and subsequent migration, the default fixture with the default install data needs to correspondingly change. I did this manually for the api/2 update, but @eosrei made the very good suggestion that a script should be written to make this easy.

Here is the code I used:

```
./manage.py dumpdata auth.permission auth.user --indent=4 > rw/fixtures/default_auth.json
./manage.py dumpdata rw --indent=4 > rw/fixtures/sample_project.json
```

As far as I know these will do the trick. Some tweaking likely necessary since the script should be stored in `roundware-server/scripts`, but should be very straight-forward.

**Comment by 13rac1** [comment]
This actually sounds like a use case for a good old Makefile. Make is the
38year old granddaddy of build systems slash task runners. Many other
little commands could collect in the file.

Here is an example from the well known Python Requests library:
https://github.com/kennethreitz/requests/blob/master/Makefile
