### ISSUE TITLE
where to find logging from roundwared processes 

### ISSUE THREAD

**Issue by probabble** [roundware/roundware-server#263]
disclaimer: this may not be a code issue as much as a developer (me) issue.

Debugging the stream manipulation is challenging because the move_listener command spawns a signal via dbus to the roundwarescript process. So normal breakpoints in the server code don't pause on the code executed after that signal is sent.

I've gotten around this by adding logging statements to the code called after that point. However, these logs _only sometimes_ appear in the stdout of the command running the server. I haven't figured out what is the real cause of this inconsistency. 

This is happening while testing against the Vagrant machine.

**Comment by probabble** [comment]
Please let me know if I need to clarify this more...

**Comment by hburgund** [comment]
@eosrei I have no idea what this is all about, but perhaps you have some thoughts or things to try? I hate these inconsistent behavior issues :-/

**Comment by 13rac1** [comment]
Roundware is a Django application. RoundwareD isn't a Django application. It's a Python application using some Django libraries.  A new forked process is started for each stream/user. I'm not surprised the Django logging loses track of the process output, I'm actually surprised it catches it in the first place.

Roundwared logs to `/var/log/roundware` just like the main roundware application. Tail that file. Settings: https://github.com/roundware/roundware-server/blob/3950fd33a371c0110d0f056607ac03b1e29c7c18/roundware/settings/common.py#L260

@hburgund Solution: In-device audio :smile:

**Comment by probabble** [comment]
Thanks, @eosrei !

**Comment by hburgund** [comment]
@probabble do you still need more info on this? If not, please close the issue...thx.
