### ISSUE TITLE
Remove sb-admin-v2 directory?

### ISSUE THREAD

**Issue by 13rac1** [roundware/roundware-server#264]
https://github.com/roundware/roundware-server/tree/c71270b2ce739c7a42c39d57d80b44391af1bb49/roundware/rw/static/dashboard/sb-admin-v2

Looks like some cruft from an old project. Document it in a git commit and remove?

**Comment by hburgund** [comment]
removing with #266 - should not have ever been committed...

**Comment by hburgund** [comment]
closed with #266
