### ISSUE TITLE
Update Travis to handle postgresql database change

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#269]
When we converted to postgres from mysql, the simple approach to Travis (using SQLite, I think?) was no longer viable. We tried a number of quick fixes to change the test db to postgres, but it seems as though there is more in depth work that needs to be done to get it to work again. 

I temporarily deactivated Travis by changing the name of `.travis.yml` so it wouldn't fail, but obviously it needs to be updated to work again as it is very helpful. I do not know enough about Travis to do the updates myself and cannot wait to get them done to merge the postgres code, unfortunately.

**Comment by 13rac1** [comment]
:( This really shouldn't be disabled. If you are purposefully breaking the tests, just let them fail.

**Comment by hburgund** [comment]
I thought it was better to have it deactivated than to have it consistently fail due to the environment not being setup properly to handle Postgres. All of the unit tests continue to work when run manually and have been updated for the Postgres changes (sadly, it's still only 51% coverage, but at least it hasn't gotten worse), but since the Travis environment isn't right, everything fails.

**Comment by 13rac1** [comment]
It's better to be straightforward about the "Failing Build" IMO.

:+1: I say just leave Travis as is. You can just remove that commit.

**Comment by hburgund** [comment]
OK, I'm fine removing that commit, but where should I indicate that we know it's failing for environmental reasons and are working on the update? Just here in this issue, or should I make it more obvious? I just don't want people looking at the GitHub page and thinking it's all crap because Travis is failing.

**Comment by hburgund** [comment]
Decision made to leave Travis in place and work to get this issue resolved asap.
