### ISSUE TITLE
Standardize APIv2 to serialize *_id for relation fields

### ISSUE THREAD

**Issue by IllyaMoskvin** [roundware/roundware-server#288]
Most of the relation-type fields that return ids are serialized in the `model_id` format. However, some are not yet serialized, simply returning `"model": id`. We need to change the latter into the former. This needs to be done in conjunction with [seeRead/roundware-ios-digita11y](https://github.com/seeRead/roundware-ios-digita11y) to avoid breaking existing features.

**Comment by hburgund** [comment]
primarily fixed by #331 and #332 
some fixes elsewhere as well
decided to standardize on `id` instead of `model_id` for model's own `id` and `model_id` rather than `model` for foreign keys.

**Comment by IllyaMoskvin** [comment]
To clarify: a model's own id is now standardized as `id`, but when a model contains a field that references another model via id, that field is standardized as `model_id`. For example, here is a sample `UI Group`:

```
{
    "id": 1,
    "name": "What genders do you want to listen to?",
    "tag_category_id": 3,
    "project_id": 1,
}
```

This also applies to more "meta" fields, e.g. preferring `parent_id` rather than `parent` when that field contains an identifier as a value.

**Comment by hburgund** [comment]
Yes, I have been making these changes as well to the vast majority of the endpoints, though there may be still some still missing. I can certainly open this issue back up if there are others you have come across that need fixing. Just let me know.
