### ISSUE TITLE
Resolve Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by IllyaMoskvin** [roundware/roundware-server#293]
Google changed their TOS: http://stackoverflow.com/questions/37991340/ 

As of June 22nd, 2016, using the Google Maps API now requires an API key. I haven't figured out an optimal solution yet. Should we require everyone who installs our app to go and get their own key, or should we provide a key with the app and risk breaking quotas?

Google Maps is still working on the `devapi` server is because it has been grandfathered, as per the link above.

This issue was discovered by @hburgund in #283. It is not, however, related to any changes made in the course of the Django 1.9 upgrade.

**Comment by 13rac1** [comment]
> Should we require everyone who installs our app to go and get their own key, or should we provide a key with the app and risk breaking quotas?

:+1: Require everyone who installs our app to go and get their own key

**Comment by IllyaMoskvin** [comment]
We should then ensure that the app fails gracefully if the key has not (yet) been provided.

**Comment by hburgund** [comment]
Fail gracefully with useful and obvious errors: "You have not yet acquired a Google Maps API key, so the map isn't working. Please go here to get one for free and then add it to your local Django settings file."

Or something like that.

But perhaps the better approach would be to ditch Google Maps in favor of Open Street Maps, which is obviously more open and I don't think requires a key? This would require some re-working of admin code, but probably wouldn't be too much effort and we are already using OSM for the new polygon speakers, so this would make things more consistent as well. I'm inclined towards this fix; thoughts?

**Comment by IllyaMoskvin** [comment]
I am unfamiliar with Open Street Maps, but it looks like a neat project. I'm inclined to use it as well. I'll make this fix a priority this coming month.

**Comment by 13rac1** [comment]
>  "You have not yet acquired a Google Maps API key, so the map isn't working. Please go here to get one for free and then add it to your local Django settings file."

I'd be fine with "Google Maps API not found." The detailed instructions can be in the README where they are easier to maintain. Google Maps has been around for ~10 years now, it shouldn't be a surprise. "Pokemon Go API key missing" would be unclear and I'd want to give more details. Haha! 🏃⚾️🎣👾🐲📲 

That being said: Open Street Maps! Yay!

**Comment by hburgund** [comment]
Let's definitely go with Open Street Maps unless we discover something that is problematic with that. Like I mentioned, we already use OSM for defining the polygons for speakers, so it's easily integrated. 

We use Leaflet and correspondingly `django-leaflet` (https://github.com/makinacorpus/django-leaflet) to help with the integration. Have a look at how it is done for the `speaker` model and I'm sure we can reproduce elsewhere relatively easily.

**Comment by hburgund** [comment]
roundware-admin uses Open Street Maps exclusively.
django admin still uses google maps, but hopefully that will be more or less deprecated soon when roundware-admin gets improved.
