### ISSUE TITLE
create and add to repo Postman collection for api/2

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#308]
this will help testing and setting up a new instance as well as future development.

Devs will have to set up their Postman environment variables properly, but having all the basic api calls  with the correct params etc at their fingertips will be very useful.

**Comment by IllyaMoskvin** [comment]
Here are the links to my current Postman collections:

APIv1: https://www.getpostman.com/collections/f1299a217ec974d144f8
APIv2: https://www.getpostman.com/collections/03f32fffe696860ec273

Now, I believe the *contents* of these links will automatically update when I make updates to the collections under my account. However, I'm not sure what happens after someone imports these collections to their account: will my updates affect their imported collections? I suspect not, but confirmation is needed.

These are also slightly out of date when it comes to audio stream manipulation. They need to be updated to reflect #299, #300, #301 (deleted), #302, and #307 (pending).

Here are the required environmental variables:

```
token:
session_id:
host:
api_port:
envelope_id:
stream_id:
```

For security reasons, I don't want to provide my values for `token`, `session_id`, `host`, and `api_port`. However, after setting up your server and entering the correct `host` and `api_port` (`localhost` and `8888` for Vagrant as per the [vagrantfile](https://github.com/roundware/roundware-server/blob/develop/Vagrantfile), iirc), you can get your `token`,  `session_id`, and `stream_id` as follows:

1. `POST` to `api/2/users`. Copy the `token` into your Postman environment.
2. `POST` to `api/2/sessions`. Copy the `session_id` into your Postman environment.
3. `POST` to `api/2/streams`. Copy the `stream_id` into your Postman environment.

It would seem that the server will assign you a constant `token`, `session_id`, and `stream_id`, so after creating a stream, you'll likely never need to modify these values, but if you restart your server, you may need to `POST` to `api/2/streams` again to restart the stream. That said, shouldn't streams and sessions time out eventually? It's not a bug, it's a feature. :stuck_out_tongue: 

I haven't really tested envelopes personally, so I'm not sure what to do with `envelope_id`; it's just been sitting around in my config for a while.
