### ISSUE TITLE
Add ability to retrieve all localized string associations via API

### ISSUE THREAD

**Issue by IllyaMoskvin** [roundware/roundware-server#311]
Related to #309. I need a way to retrieve *all* localized messages associated with... well, just about everything, but `Tags` most urgently. Currently, e.g. `api/2/projects/:id/tags` and `api/2/tags` returns only the `loc_description` and `loc_msg` for the language associated with the current session.

This is a major blocker. I will need a field similar to the `relationships` field on `Tag`. We can keep the `loc_` fields for now to avoid breaking the iOS app, but we should also consider whether they ought to be deprecated.

Now, there are several different ways we can go about this. Here is a sample `Tag` response illustrating what I need:

```
{
  "id": 42,
  "value": "Intro",
  "description": "Introduction",

  [irrelevant fields omitted]

  // OPTION 1
  "loc": [
    {
      "id": 1,
      "field": "value",
      "text": "Intro",
      "language": {
        "id": 1,
        "code": "en"
      }
    },
    {
      "id": 2,
      "field": "description",
      "text": "Introduction",
      "language": {
        "id": 1,
        "code": "en"
      }
    },
    {
      "id": 3,
      "field": "value",
      "text": "Intro",
      "language": {
        "id": 2,
        "code": "es"
      }
    },
    {
      "id": 4,
      "field": "description",
      "text": "Introducción",
      "language": {
        "id": 2,
        "code": "es"
      }
    },
  ]

  // OPTION 2
  "loc": [
    {
      "id": 1,
      "code": "en",
      "field": "value",
      "text": "Intro",
    },
    {
      "id": 2,
      "code": "en",
      "field": "description",
      "text": "Introduction"
    },
    {
      "id": 3,
      "code": "es",
      "field": "value",
      "text": "Intro"
    },
    {
      "id": 4,
      "code": "es",
      "field": "description",
      "text": "Introducción"
    },
  ]

  // OPTION 3
  "loc": {
    "en": [
      {
        "id": 1,
        "field": "value",
        "text": "Intro"
      },
      {
        "id": 2,
        "field": "description",
        "text": "Introduction"
      }
    ],
    "es": [
      {
        "id": 3,
        "field": "value",
        "text": "Intro"
      },
      {
        "id": 4,
        "field": "description",
        "text": "Introducción"
      }
    ]
  ]

  // OPTION 4
  "loc": {
    "en": {
      "value": {
        "id": 1,
        "text": "Intro",
      },
      "description": {
        "id": 2,
        "text": "Introduction",
      },
    },
    "es": {
      "value": {
        "id": 3,
        "text": "Intro"
      },
      "description": {
        "id": 4,
        "text": "Introducción",
      }
    }
  }
```

Surprisingly, I like `OPTION 4` the best. It makes accessing localized string so easy: `tag.loc.en.description`. The only problem is that the language code is changeable via the admin, while the dot-notation reference would be hard-coded into the client app. Most of these solutions also require that we enforce variable-name conventions onto `language_code` (no special characters). I don't much care which option is chosen, though, as long as I have some way to (1) retrieve the language `id`, either through `language_code` lookup or directly from the `Tag` serialization, and (2) retrieve the `id` of the `LocalizedString`.

I could hack around the lack of this response by retrieving the `loc_` fields returned by the API, then querying an API endpoint for localized strings to correlate the value of that field with the `localized_string` field of `LocalizedString` (I think that field deserves a shorter name)... but (1) we don't have an `api/2/loc` or similar endpoint defined, and (2) the "Intro" example illustrates how an identical string could return multiple results, so even if I hard-code the admin to only modify the first result it finds, without an `id` value, there is no guarantee that I'll be modifying the correct string.

I'm also not entirely sure why there are two `loc_` fields. In the example above, I'm assuming that the `loc_msg` field meant to be the localized "short" tag name (i.e. `Intro`) and the `loc_description` field is meant to be the localized long-form description or full name (i.e. `Introduction`). On the devapi server, none of the tags have a non-null `loc_description` AFAICT! But this concern is secondary to the main issue at hand: being able to retrieve *all* associated `LocalizedString`s for each `Tag`.

**Comment by IllyaMoskvin** [comment]
> The only problem is that the language code is changeable via the admin, while the dot-notation reference would be hard-coded into the client app. Most of these solutions also require that we enforce variable-name conventions onto `language_code` (no special characters).

This can be mitigated by restricting the set of possible codes to Django's standard `LANGUAGES` setting. This is hinted at by the Django REST Framework's docs on internationalization, and it seems that `django-modeltranslation` relies on that setting as well ([docs](https://django-modeltranslation.readthedocs.io/en/latest/installation.html#languages)). However, this means that the set of possible `LANGUAGES` must be hard-coded into the app.

Furthermore, it seems that `django-modeltranslation` would [dynamically create columns](http://stackoverflow.com/a/22557676/1943591) for each language specified. Someone will need to look into this further, but I suspect that if we decide to hard-code the widest possible array of `LANGUAGES`, `django-modeltranslation` would create an obscene number of columns, most of them null. If it creates columns on-demand, i.e. when you first specify a value for some language for some field, that's definitely more bearable, even if it doesn't clean up for itself when the last value is removed for a given field, for some language, for all entities of that class.

Just thinking out loud at this point.

**Comment by hburgund** [comment]
IIRC, the way Roundware works for localization now is that it determines the language of the device from a param sent in the initial `POST api/2/sessions/` call. From that point on, all responses include only the `_loc` values associated with the session language. This makes the client codebase simpler at the expense of a bit of server complexity, though obviously, it could be done either way.

I am hesitant to change this approach right now given our uncertainty about the ultimate best solution for localization. As you suggest, we can just add more pieces to the responses that include all available language localized strings, but that isn't overly elegant, unfortunately.

I wonder if there is a way to do it in "reverse", by creating a `localizedstring/` endpoint and somehow traversing to `tags` (or other model) that way. We could then have endpoints like:

* `localizedstring/tags/` with `project_id` as a param
* `localizedstring/uigroup/` with `project_id` as a param

Or maybe it's better to just have one endpoint that is filterable by project and is organized at the top level by `tags` `uigroups` `project` `assets` (I believe these are the only models that currently use `_loc` fields.

I don't know what's best; just thinking it through and tossing out some early ideas. I'll continue to ponder.

**Comment by jslootbeek** [comment]
On a call with Halsey, I prototyped our solution. We added a query parameter to the existing endpoints which, if included, will add all the localized strings to the endpoint. See the implementation [here](https://github.com/jslootbeek/roundware-server/commit/0460bb27adb5edbebb20501c51a4777617cd0434). 

Here's the return without the query parameter ```api/2/projects/1/tags/```:

```
{
    "tags": [
        {
            "id": 3,
            "value": "male",
            "description": "male",
            "data": "class=tag-one",
            "filter": "",
            "location": null,
            "project": 1,
            "tag_category": 3,
            "loc_description": null,
            "loc_msg": "male",
            "relationships": []
        },
        {
            "id": 4,
            "value": "female",
            "description": "female",
            "data": "class=tag-one",
            "filter": "",
            "location": null,
            "project": 1,
            "tag_category": 3,
            "loc_description": null,
            "loc_msg": "female",
            "relationships": []
        }
    ]
}
```

and result with the query parameter ```api/2/projects/1/tags/?admin=1```:
```

{
    "tags": [
        {
            "id": 3,
            "all_msg": [
                {
                    "id": 5,
                    "language": "en",
                    "localized_string": "male"
                },
                {
                    "id": 6,
                    "language": "es",
                    "localized_string": "hombre"
                }
            ],
            "all_desc": [],
            "value": "male",
            "description": "male",
            "data": "class=tag-one",
            "filter": "",
            "location": null,
            "project": 1,
            "tag_category": 3,
            "loc_description": null,
            "loc_msg": "male",
            "relationships": []
        },
        {
            "id": 4,
            "all_msg": [
                {
                    "id": 7,
                    "language": "en",
                    "localized_string": "female"
                },
                {
                    "id": 8,
                    "language": "es",
                    "localized_string": "mujer"
                }
            ],
            "all_desc": [],
            "value": "female",
            "description": "female",
            "data": "class=tag-one",
            "filter": "",
            "location": null,
            "project": 1,
            "tag_category": 3,
            "loc_description": null,
            "loc_msg": "female",
            "relationships": []
        }
    ]
}
```

**Comment by IllyaMoskvin** [comment]
@jslootbeek This looks good to me. I understand it might not be a forever-solution, but for the foreseeable future, I can definitely work with this. Thank you!

**Comment by hburgund** [comment]
Here is the official list of fields that have localization and therefore need to be implemented into the API:
* `asset.loc_description`
* `asset.loc_alt_text`
* `project.demo_stream_message_loc`
* `project.legal_agreement_loc`
* `project.sharing_message_loc`
* `project.out_of_range_message_loc`
* `tag.loc_description`
* `tag.loc_msg`
* `uigroup.header_text_loc`

All of these are `ForeignKey` fields to the `LocalizedString` model, so they are easy to segment collectively.

**Comment by hburgund** [comment]
Basic testing yields:
* Working: `projects/`, `projects/tags/`, `projects/1/uigroups/`, `projects/1/assets/`
* NOT working: `uigroups/`, `assets/`, `tags/`

Serializer mixin is currently only working for `projects/*` endpoints. It can easily be extended, but my inclination is to not extend it as this is a use-case specific to the admin and the admin doesn't need multiple options. @IllyaMoskvin please let us know what you think.

**Comment by jslootbeek** [comment]
To make those other views accept this, you can add the admin variable into the context that gets passed to the serializer. 
`serializer = serializers.TagSerializer(tags, context={"session": session, "admin": "admin" in request.query_params}, many=True)`
