### ISSUE TITLE
handle blocked assets for client-side mixing

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#374]
For client-side mixing, we need to be able to implement blocked assets for each user. We will capture and store data about blocked assets and users on the server as we currently do, but we need a way for the client to take this data into account when playing assets. I see two possible approaches:

* Retrieve from the server a list of `asset_ids` that a particular user has blocked either by blocking the asset itself or by blocking the user who created the asset. This would be a new API call that would serve as the basis for a new playlist filter.
* Or when the user initially retrieves the asset pool from the server when they open a session, the server does the filtering at that point. This would mean that the client never gets any data at all about blocked assets. This seems like a better approach though there may be some complications with a user blocking another user who already has an asset in the asset pool.

Currently this blocking takes place entirely on the server.

**Comment by loafofpiecrust** [comment]
It would probably be a similar effort either way, right? If implemented on the server, we can just request the asset pool again when the user makes a banning vote. This is a bit simpler for the client side, but grabbing the asset pool again is slower than just adding a ban to a list.
It's possible to do it on the client with an encapsulated filter and that would be more consistent with the ideology of doing all filtering on the client. The list of bans is grabbed at start, then when the user bans an asset or user, we  send that vote to the server and add it to our local list so that only that vote API call has to be made and we don't have to request the asset pool again.

**Comment by hburgund** [comment]
OK, I like the consistency of having all asset filtering happening on the client within the new filter architecture. So we'll go with the first of my two options above:

* create new API call `GET assets/blocked/` that takes `username` as a param
* API response is array of blocked assets
* blocked assets stored locally on client 
* new `BlockedAssetsFilter` performs asset pool filtering for `Playlist`

@loafofpiecrust LMK if this makes sense to you as the best way to proceed. I think the hardest part may be on the server, but shouldn't be too bad. I'll bounce ideas off of you for JSON format of the response etc.

**Comment by hburgund** [comment]
@loafofpiecrust I have created a new API call: `GET /api/2/assets/blocked/` which takes the standard `session_id` as its sole parameter.
The server then figures out what user is associated with the `session_id` and traverses all the way to what `asset_ids` were directly (ie `block_asset` vote cast) or indirectly (ie `block_user` vote cast) blocked and returns those in a JSON object.
The current format for the JSON response is:
```
{
    "device_id": "c88a2d87-1501-4e6a-88d3-125b346e6e91",
    "blocked_asset_ids": [
        1,
        3
    ]
}
```
I only returned an array of `asset_ids` rather than an array of `asset` objects as I don't think any other asset data is needed by the client. I included the `device_id` for no clear use at this point, but having that in the response seemed like a good way to identify what the list of blocked assets applied to.

Please let me know if this seems reasonable and if there are modifications to the response format or anything else you think could be improved. 
I can then make the adjustments and deploy to the production server so you'll be able to implement the call and create the new `BlockedAssetsFilter` filter on the client.

**Comment by loafofpiecrust** [comment]
@hburgund This looks good to me. We should only need the asset IDs on the client side, so that response will work. Just to make sure, we shouldn't have issues with accidental project overlap on the same server here right?

**Comment by hburgund** [comment]
@loafofpiecrust each asset is assigned to only one project (not sure I understand exactly what you're asking?).

also, if a user happens to have two RW-based apps installed on their iOS device, there will be different `device_ids` for the different apps, which will ensure that blocking an asset for one project doesn't affect another project, afaict.
