### ISSUE TITLE
invalid syntax error on -m install mod_wsgi

### ISSUE THREAD

**Issue by kris-boyd** [roundware/roundware-server#409]
while installing, I get this error:

python3 -m pip install mod_wsgi
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

on fresh install of ubuntu 16.04 on remote server (Linode)

**Comment by hburgund** [comment]
sorry, our documentation is woefully out of date, but please give the current `develop` branch a shot on a fresh install of Ubuntu 20.04. I'm not sure if your issue is related to the older Ubuntu, but the newest code is built for 20.04, so let's start there and see how it goes. LMK.

**Comment by kris-boyd** [comment]
Install Completed fully on Ubuntu 20.04

**Comment by hburgund** [comment]
Great; thx for reporting back. I will close this issue and update our docs some :-/
