### ISSUE TITLE
create 'asset-edit-map' custom view

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#63]
Basically this is a visual, mapped version of the Asset list view editor of the Admin. 
- voice map that lays out all voices for a particular project (would be awesome to be able to select which project and have the map refresh)
- each pin can be listened to and moved, rearranged
- eventually listening radius is adjustable as well once we have that feature, but for now, standard radius is displayed for each
- basic asset info in popup with audio player
- Save button saves all at once (or saving done with AJAX calls)

We already have a listen-map created which creates the display of assets on a map with all the radius and info window stuff.  We just need to add to it the ability to move each asset and save the lat/lon for them.  listen-map.html and associated files are in the roundware-web-base repo on bitbucket.

This will be amazingly useful for sculpting the audio experience holistically rather than one asset at a time.

**Comment by eosrei** [comment]
Further details from  @hburgund regarding the asset-map
>Hopefully you can use this to devise a unit test so we get better coverage.
It’s really very simple and gets installed automatically.  The file is here:

>roundware/rw/templates/asset-map.html

>and it can be accessed at:

>http://localhost:8888/dashboard/asset-map?project=1

>if you leave out the project_id parameter, it will include all projects.
>Once you hit that url, you can move the pin for the default asset by dragging it and then check in the admin to see if the coordinates changed accordingly.

>The ‘savePosition’ function does a PATCH AJAX call to handle the coordinate change, so that’s probably one of the tests you’ll want to add along with the drawPoints function that uses the assetlocation API endpoint to get the data for displaying the current state of the markers.

**Comment by hburgund** [comment]
#286 handles some nice updates here; some features listed above are still not incorporated, but will create new issues as needed since this one is large and a bit vague and is now quite stale.
