### ISSUE TITLE
add button in Admin for the Master UI Tag organization form

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#66]
ie this page:

http://localhost/rw/masteruis/setup_tag_ui/

And I think the button to access that page should be either on the UI Mappings page next to Add UI Mapping or potentially on the main RW admin screen next to the Add and Change icons for the UI Mappings row?

What would be best is a quick hint on how I can do this myself so I can learn.  I'm guessing it's pretty easy and I know html/css/js fairly well.  I am planning to just look at how you did it for the Batch Tags form, but any hints are welcome.

**Comment by bryanlandia** [comment]
OK, Halsey.  Will do.

**Comment by hburgund** [comment]
deprecated

**Comment by hburgund** [comment]
I'm closing this as the new external custom admin system will handle the tag organization so this form will not be needed.
