### ISSUE TITLE
replace dbus with more modern inter-process messaging system

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#83]
RabbitMQ: http://www.rabbitmq.com/
ActiveMQ: http://activemq.apache.org/
ZeroMQ: http://zeromq.org/

We need a solution that is a bit more robust, modern and less touchy than dbus has been.  There are likely other options, but these three seem to all be well-used and supported, so they are a good place to start.

**Comment by eosrei** [comment]
Doesn't matter if/when we have full In-Device audio and can remove roundwared. Adding to that milestone since related.

**Comment by hburgund** [comment]
I'm not convinced that implementing in-device audio mixing will immediately mean we will want to remove ```roundwared```.  For one, all web clients would require the same re-write to mix audio in the browser which I'm sure is possible, but isn't likely to happen very soon.

And there may continue to be reasons that in certain circumstances, the current server-mixing still makes the most sense.

Don't get me wrong, in-device audio mixing is going to be fantastic; I just think we'll need/want to offer both options, at least for a while.  Whether or not this merits the effort to implement a new inter-process messaging system, I cannot say for sure, but it seems reasonable to just stick with dbus since server-based audio mixing will certainly be less prevalent in the future.

**Comment by eosrei** [comment]
> at least for a while
Yes I expect both for a bit.

I expect we'll be writing a mixer in Javascript for web clients. Once all three (JS, Java, Swift) are creating audio streams, we can consider removing roundwared. It won't be soon, but dbus works well enough now.

**Comment by hburgund** [comment]
Web mixing would be fantastic!  Yes, once all three are in place (along with any others that crop up ;-) ), we should certainly consider removing ```roundwared``` or the portions of it that have been replaced.

Given this approach, should we just close this issue?

**Comment by eosrei** [comment]
Yes
